# Generated by Django 4.2.17 on 2024-12-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0005_alter_journals_pdffile_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('INSTITUTE', 'Institute'), ('TEACHER', 'Teacher')], max_length=20),
        ),
    ]
